### ISSUE TITLE
Adding extra commands (not available right now)

### ISSUE THREAD

**Issue by AmitJomy001** [dankgrinder/dankgrinder#119]
please add these following commands 
'pls use alcohol'
'pls use luckyhorseshoe'          #don't forget to add the button confirm.

Thanks
and a question : how do we give the name/id of the account to which the grinded items should be autogifted ?

**Comment by sneazy-ibo** [comment]
> please add these following commands 'pls use alcohol' 'pls use luckyhorseshoe' #don't forget to add the button confirm.
> 
> Thanks and a question : how do we give the name/id of the account to which the grinded items should be autogifted ?

There is literally a custom commands section where you can input those commands.

They don't need to add the confirm button, just type `pls settings confirmations nah` in the custom commands and everything should be alright.

The master instance gets all the items if you have the auto_gift feature enabled:

```yaml
clusters:
  default:
    master:
      token: "your main or what ever" #this acc gets the items
      channel_id: "791694339116892202"
    instances:
      - token: "alt acc" #shares items
        channel_id: "791694383098495047"
      - token: "alt acc" #shares items
        channel_id: "791694383098495048"
```
