### ISSUE TITLE
bot doesn't start succesfully

### ISSUE THREAD

**Issue by sotongboi** [dankgrinder/dankgrinder#124]
**Expected behavior**
bot working normally

**Actual behavior**
error appears

**Logs**
{"level":"info","msg":"starting cluster default","time":"2022-04-25T10:35:34+08:00"}
{"level":"info","msg":"successful authorization as sotongboi#3976","time":"2022-04-25T10:35:35+08:00"}
{"cluster":"default","instance":"sotongboi#3976","level":"error","msg":"instance fatal: scheduler fatal: scheduler fatal: forbidden, you may not have permission to send in the channel (i.e. you aren't in the server or don't have send message permissions in the channel), your account might need verification, or your ip address may have been blocked","time":"2022-04-25T10:35:38+08:00"}
{"level":"fatal","msg":"no running instances left","time":"2022-04-25T10:35:38+08:00"}

**Environment**
OS: Windows,
Dank Grinder version: Buttons v2.1.0
Config: make sure to remove your tokens! E.g.
```yaml
instances:
  - token: ""
    channel_id: ""
    shifts:
      - state: "active"
        duration:
          base: 0
          variance: 0

features:
  commands:
    fish: true
    hunt: true
  custom_commands:
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
  auto_sell:
    enable: false
    interval: 0
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: false
    to: ""
    interval: 0
    items:
      - "kn"
      - "zz"
  balance_check: true
  log_to_file: true
  debug: false

compatibility:
  postmeme:
    - "f"
    - "r"
    - "i"
    - "c"
    - "k"
  allowed_searches:
    - "bus"
    - "coat"
    - "dresser"
    - "grass"
    - "laundromat"
    - "mailbox"
    - "pantry"
    - "pocket"
    - "shoe"
    - "sink"
    - "car"
  search_cancel:
    - "no"
    - "bad options"
    - "i don't want to die"
    - "stop"
    - "."
  cooldown:
    beg: 45
    search: 30
    highlow: 20
    postmeme: 60
    fish: 60
    hunt: 60
    margin: 3
  await_response_timeout: 4

suspicion_avoidance:
  typing:
    base: 0
    variance: 250
    speed: 450
  message_delay:
    base: 100
    variance: 400
```
![image](https://user-images.githubusercontent.com/94187885/165011998-302635e7-e7c8-4928-9c4d-4df45433607f.png)
