### ISSUE TITLE
How do I use the auto_share option in the config?

### ISSUE THREAD

**Issue by Official-Darkn** [dankgrinder/dankgrinder#15]
I have 2 other alts that are actively autofarming coins and I want those alts to give all of its coins to my main, how would I do that as I'm not sure how to use the auto_share option in the config, as I set it to true but I'm not sure what else to do.

**Comment by OsOmE1** [comment]
[](https://github.com/dankgrinder/dankgrinder#auto-share-object)
"to the master instance"
[](https://github.com/dankgrinder/dankgrinder#instances)
`is_master: true`

Read carefully next time.

**Comment by Explsn** [comment]
Is it somehow possible to share to an independent account with auto share, without setting master?
My intention is to create a gamble bot, so the master shouldnt gamble but my other account should

**Comment by dankgrinder** [comment]
> Is it somehow possible to share to an independent account with auto share, without setting master?
> My intention is to create a gamble bot, so the master shouldnt gamble but my other account should

You can override the config for the master instance only. Most of what I'm about to cover you can also find at the [default values and when you can leave out fields documentation](https://github.com/dankgrinder/dankgrinder#default-values-and-when-you-can-leave-out-fields) and [instance object documentation](https://github.com/dankgrinder/dankgrinder#instance-object)

Say, for example, your instances configuration looks like this:
```yaml
instances:
  - token: "masterinstancetoken"
    channel_id: "0123456789"
    is_master: true
  - token: "token2"
    channel_id: "0123456789"
  - token: "token3"
    channel_id: "0123456789"
  - token: "token4"
    channel_id: "0123456789"
// and so on
```

and your auto-bet and auto-tidepod configuration like this:
```yaml
auto_bet:
  enable: true
  priority: true
  pause_below_balance: 1000000
auto_tidepod:
  enable: true
  buy_lifesaver_on_death: true
```

Now you don't want your master instance to use tidepods or bet because you store a significant amount of money there. You can override the config for only the master instance like this:
```yaml
instances:
  - token: "masterinstancetoken"
    channel_id: "0123456789"
    is_master: true
    features:
      auto_bet:
        enable: false
      auto_tidepod:
        enable: false
  - token: "token2"
    channel_id: "0123456789"
  - token: "token3"
    channel_id: "0123456789"
  - token: "token4"
    channel_id: "0123456789"
// and so on
```

The master instance now uses the regular config the rest of your instances uses, except for `features.auto_bet.enable` and `features.auto_tidepod.enable` which have both been set to `false`.

You can also disable the master instance altogether like this:
```yaml
instances:
  - token: "masterinstancetoken"
    channel_id: "0123456789"
    is_master: true
    shifts:
      - state: "dormant"
  - token: "token2"
    channel_id: "0123456789"
  - token: "token3"
    channel_id: "0123456789"
  - token: "token4"
    channel_id: "0123456789"
// and so on
```
