### ISSUE TITLE
BJ Instance does not read the card value

### ISSUE THREAD

**Issue by georgeous11** [dankgrinder/dankgrinder#24]
**Expected behavior**
Message logger should read hand total value, and use the logic table to respond with hit or stand

**Actual behavior**
PLS BJ 100000 would transmit, and the command will get run over by another command. voiding the bj bet

**Steps to reproduce**
after personal details. Disable all commands except BJ, and bal check. Match BJ Instance as follows:
auto_blackjack:
    enable: true
    priority: false
    amount: 100000
    logic_table:

**Logs**
--personal tag removed and replaced with "player"--
<details><summary>Logs</summary>

```
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:09:57-05:00"}
{"delay":"461ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:09:58-05:00","typing":"1.052s"}
{"delay":"327ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:10:18-05:00","typing":"1.018s"}
{"delay":"470ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:10:37-05:00","typing":"1.071s"}
{"delay":"400ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:10:56-05:00","typing":"976ms"}
{"level":"fatal","msg":"invalid config: invalid auto-blackjack logic table key: 1","time":"2021-03-30T03:12:03-05:00"}
{"level":"fatal","msg":"invalid config: invalid auto-blackjack logic table key: 1","time":"2021-03-30T03:12:05-05:00"}
{"level":"fatal","msg":"invalid config: invalid auto-blackjack logic table key: 1","time":"2021-03-30T03:12:05-05:00"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:12:25-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:12:25-05:00"}
{"delay":"256ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:12:25-05:00","typing":"1.144s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:12:36-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:12:36-05:00"}
{"delay":"289ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:12:38-05:00","typing":"987ms"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:13:41-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:13:41-05:00"}
{"delay":"156ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:13:42-05:00","typing":"998ms"}
{"delay":"490ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:13:43-05:00","typing":"2.781s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:17:27-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:17:27-05:00"}
{"delay":"299ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:17:28-05:00","typing":"974ms"}
{"delay":"323ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:17:29-05:00","typing":"2.871s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:18:04-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:18:04-05:00"}
{"delay":"494ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:18:05-05:00","typing":"1.038s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:18:26-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:18:26-05:00"}
{"delay":"160ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:18:27-05:00","typing":"1.13s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:19:04-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:19:04-05:00"}
{"delay":"188ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:19:04-05:00","typing":"1.101s"}
{"delay":"293ms","level":"info","msg":"responding to global event: draw","time":"2021-03-30T03:19:06-05:00","typing":"536ms"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:19:31-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:19:31-05:00"}
{"delay":"147ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:19:32-05:00","typing":"1.09s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:19:59-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:19:59-05:00"}
{"delay":"332ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:20:00-05:00","typing":"1.056s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:20:23-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:20:23-05:00"}
{"delay":"306ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:20:23-05:00","typing":"1.177s"}
{"delay":"481ms","level":"info","msg":"responding to global event: chug","time":"2021-03-30T03:20:25-05:00","typing":"721ms"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:24:04-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:24:04-05:00"}
{"delay":"302ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:24:04-05:00","typing":"1.06s"}
{"delay":"487ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:24:06-05:00","typing":"2.879s"}
{"delay":"194ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:24:22-05:00","typing":"2.8s"}
{"delay":"492ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:24:31-05:00","typing":"1.019s"}
{"delay":"470ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:24:38-05:00","typing":"2.691s"}
{"delay":"415ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:24:50-05:00","typing":"1.114s"}
{"delay":"173ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:24:54-05:00","typing":"2.804s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:25:22-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:25:22-05:00"}
{"delay":"414ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:25:22-05:00","typing":"1.138s"}
{"delay":"242ms","level":"info","msg":"sending command: pls blackjack 100000","time":"2021-03-30T03:25:24-05:00","typing":"2.816s"}
{"level":"info","msg":"successful authorization as player","time":"2021-03-30T03:41:21-05:00"}
{"duration":21600000000000,"level":"info","msg":"starting shift 1","state":"active","time":"2021-03-30T03:41:21-05:00"}
{"delay":"143ms","level":"info","msg":"sending command: pls bal","time":"2021-03-30T03:41:22-05:00","typing":"1.119s"}
```

</details>

**Environment**
OS: Windows 10.0.19042
Dank Grinder version: 0.10.1

Config: 
<details><summary>Config</summary>

```yaml
instances:
  - token: ""
    channel_id: ""
    shifts:
  - state: "active"
    duration:
      base: 21600
  - state: "dormant"
    duration:
      base: 32400

features:
  commands:
    beg: false
    postmeme: false
    search: false
    highlow: false
    fish: false
    hunt: false
  custom_commands:
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
  auto_sell:
    enable: false
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: false
    items:
      - "bank"
      - "pizza"
  auto_share:
    enable: false
    maximum_balance: 8000000
    minimum_balance: 5000000
  auto_blackjack:
    enable: true
    priority: false
    amount: 100000
    logic_table:
      2:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "stand"
        16: "stand"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      3:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "stand"
        16: "stand"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      4:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "stand"
        15: "stand"
        16: "stand"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      5:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "stand"
        15: "stand"
        16: "stand"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      6:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "stand"
        15: "stand"
        16: "stand"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      7:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "hit"
        16: "hit"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "stand"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      8:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "hit"
        16: "hit"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "hit"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      9:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "hit"
        16: "hit"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "hit"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      10:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "hit"
        16: "hit"
        17: "stand"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "hit"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
      A:
        4: "hit"
        5: "hit"
        6: "hit"
        7: "hit"
        8: "hit"
        9: "hit"
        10: "hit"
        11: "hit"
        12: "hit"
        13: "hit"
        14: "hit"
        15: "hit"
        16: "hit"
        17: "hit"
        18: "stand"
        19: "stand"
        20: "stand"
        soft12: "hit"
        soft13: "hit"
        soft14: "hit"
        soft15: "hit"
        soft16: "hit"
        soft17: "hit"
        soft18: "stand"
        soft19: "stand"
        soft20: "stand"
  auto_tidepod:
    enable: false
    buy_lifesaver_on_death: true
  balance_check:
    enable: true
    interval: 18
  log_to_file: true
  debug: false

compatibility:
  postmeme:
    - "f"
    - "r"
    - "i"
    - "c"
    - "k"
  allowed_searches:
    - "bus"
    - "coat"
    - "dresser"
    - "grass"
    - "laundromat"
    - "mailbox"
    - "pantry"
    - "pocket"
    - "shoe"
    - "sink"
  search_cancel:
    - "no"
    - "bad options"
    - "i don't want to die"
    - "stop"
    - "."
  cooldown:
    beg: 48
    search: 38
    highlow: 33
    postmeme: 63
    fish: 63
    hunt: 63
    blackjack: 13
    sell: 6
    gift: 26
  await_response_timeout: 6

suspicion_avoidance:
  typing:
    variation: 250
    speed: 450
  message_delay:
    base: 100
    variation: 400
```

</details>
