### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Abhinav-ranish** [dankgrinder/dankgrinder#29]
**Expected behavior**
It Supposed to start and log commands

**Actual behavior**
It Starts And Closes

**Steps to reproduce**
I tired with a new installation and it still had same issue

**Logs**
If relevant, paste any errors or other logs here.

**Environment**
OS: e, Windows, 
Dank Grinder version: latest one 6/4/21
Config: 
```yaml
instances:
  - token: ""
    channel_id: ""
    shifts:
      - state: "active"
        duration:
          base: 0
          variance: 0

features:
  commands:
    fish: true
    hunt: true
  custom_commands:
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
  auto_sell:
    enable: false
    interval: 0
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: false
    to: ""
    interval: 0
    items:
      - "kn"
      - "zz"
  balance_check: true
  log_to_file: true
  debug: false

compatibility:
  postmeme:
    - "f"
    - "r"
    - "i"
    - "c"
    - "k"
  allowed_searches:
    - "bus"
    - "coat"
    - "dresser"
    - "grass"
    - "laundromat"
    - "mailbox"
    - "pantry"
    - "pocket"
    - "shoe"
    - "sink"
    - "car"
  search_cancel:
    - "no"
    - "bad options"
    - "i don't want to die"
    - "stop"
    - "."
  cooldown:
    beg: 45
    search: 30
    highlow: 20
    postmeme: 60
    fish: 60
    hunt: 60
    margin: 3
  await_response_timeout: 4

suspicion_avoidance:
  typing:
    base: 0
    variance: 250
    speed: 450
  message_delay:
    base: 100
    variance: 400
```
