### ISSUE TITLE
Await Resume Timed Out for no reason

### ISSUE THREAD

**Issue by DARKPLASMA** [dankgrinder/dankgrinder#66]
**Expected behavior**
Normal Behavior

**Actual behavior**
Await Resume Timed Out

**Steps to reproduce**
Happens on Installation

**Logs**
Note: All Name and Tags have been removed from the log as to not reveal my identity.

ERRO[0016] await resume timed out for: pls search

{"level":"info","msg":"starting cluster default","time":"2021-05-29T15:37:37-04:00"}
{"level":"info","msg":"successful authorization as","time":"2021-05-29T15:37:37-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:37:51-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls hl","time":"2021-05-29T15:37:59-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:38:31-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls hl","time":"2021-05-29T15:38:39-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:39:10-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls fish","time":"2021-05-29T15:39:19-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:39:50-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls pm","time":"2021-05-29T15:39:59-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:40:30-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls hunt","time":"2021-05-29T15:40:39-04:00"}
{"cluster":"default","instance":"","level":"error","msg":"await resume timed out for: pls search","time":"2021-05-29T15:41:10-04:00"}

**Environment**
OS: Chrome OS with the Linux Beta Sandbox
Dank Grinder version: 0.11.0
Config: make sure to remove your tokens! E.g.
```yaml
clusters:
  default:
    master:
      token: ""
      channel_id: ""

shifts:
  - state: "active"
    duration:
      base: 7200
      variation: 1800
  - state: "dormant"
    duration:
      base: 1800
      variation: 1800

features:
  commands:
    beg: true
    postmeme: true
    search: true
    highlow: true
    fish: true
    hunt: true
  custom_commands:
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
  auto_sell:
    enable: false
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: false
    items:
      - "bank"
      - "pizza"
  auto_share:
    enable: false
    maximum_balance: 8000000
    minimum_balance: 5000000
  auto_blackjack:
    enable: false
    pause_below_balance: 1000000
    logic_table:
      2:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      3:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      4:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      5:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      6:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      7:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      8:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      9:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      10:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      A:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "h"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
  auto_tidepod:
    enable: false
    buy_lifesaver_on_death: true
  balance_check:
    enable: true
    interval: 180
  log_to_file: true
  verbose_log_to_stdout: false
  debug: false

compatibility:
  postmeme:
    - "f"
    - "r"
    - "i"
    - "c"
    - "k"
  allowed_searches:
    - "bus"
    - "coat"
    - "dresser"
    - "grass"
    - "laundromat"
    - "mailbox"
    - "pantry"
    - "pocket"
    - "shoe"
    - "sink"
  search_cancel:
    - "no"
    - "bad options"
    - "i don't want to die"
    - "stop"
    - "."
  cooldown:
    beg: 48
    search: 38
    highlow: 33
    postmeme: 63
    fish: 63
    hunt: 63
    blackjack: 13
    sell: 6
    gift: 26
    share: 13
  await_response_timeout: 7

suspicion_avoidance:
  typing:
    variation: 250
    speed: 450
  message_delay:
    base: 100
    variation: 400
```
